server:
  port: 8011

spring:
  application:
    name: mydream
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: zxcvbnm,.
    username: root
    url: jdbc:mysql://localhost:3306/mydream?autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
logging:
  level:
    com.lin.mydream.mapper: debug


robot:
  ding:
    - f0676f432ae1da77af9a6219296982c23741ae23ea6f7638bc4bfebfb8d8771a,SECc99725f7915d0314e7c77eed43f51376c47736116ae567374f3fb3f4544a1a6c,e49f5b,true

tencent:
  secret-id: AKIDnQmsiHZaMr52jALFsFK8gz1mFSO3SaR2
  secret-key: MRGo55pIUP3RYOxGaeRxCAqFOGrBF1Wl

chat-gpt:
  api-key: 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
  max-tokens: 1000
  temperature: 0.5
